apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: live-stream
  labels:
    app: frontend-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: frontend-web
