apiVersion: v1
kind: PersistentVolume
metadata:
  name: redpanda-pv
  labels:
    type: local
    app: redpanda
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redpanda"
