apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-pvc
  namespace: live-stream
  labels:
    app: redpanda
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
