apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  namespace: live-stream
  labels:
    app: redpanda
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-outside
    - port: 29092
      targetPort: 29092
      name: kafka-internal
    - port: 8081
      targetPort: 8081
      name: schema-registry
    - port: 8082
      targetPort: 8082
      name: pandaproxy
  selector:
    app: redpanda
