apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: live-stream
data:
  PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service"
  MEETING_SERVICE_URL: "http://meeting-service"
  SIGNALING_SERVICE_URL: "http://signaling-service"
