apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: live-stream
data:
  PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  MEETING_SERVICE_URL: "http://meeting-service:4002"
  SIGNALING_SERVICE_URL: "http://signaling-service:4003"
